version: "3.9"

services:
  # 1) PostgreSQL
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n123
      POSTGRES_DB: chatbot
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d chatbot"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"   # <- EXPÕE PARA SEU SGBD

  # 2) n8n
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Base
      - N8N_HOST=n8n.localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=America/Fortaleza

      # DB
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=chatbot
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n123

      # URLs (opcional, útil com proxy)
      - WEBHOOK_URL=http://n8n.localhost/
      - N8N_EDITOR_BASE_URL=http://n8n.localhost/
    volumes:
      - n8n_data:/home/node/.n8n

  # 3) Nginx (Proxy Reverso)
  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - n8n
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  dbdata:
  n8n_data:
